Initial project: Alien invasion - first
logiflo/python-playground pull request #1
Opened 2020-06-24 14:35 UTC by logiflo

2020-06-24 16:23 UTC, feserr requested changes

2020-06-24 16:23 UTC, feserr commented on AlienInvasion/alien_invasion.py
> +    ship = Ship(ai_settings, screen)
Why sending the screen for set the position of the ship? It should be better to use a X and Y variables.

2020-06-24 16:23 UTC, feserr commented on AlienInvasion/game_functions.py
> +def update_screen(ai_settings, screen, ship):
This should be named as "draw_screen".

2020-06-24 16:23 UTC, feserr commented on AlienInvasion/ship.py
> +        self.rect.centerx = self.screen_rect.centerx
Use the X and Y variables as told before.

2020-06-25 09:43 UTC, logiflo commented on AlienInvasion/alien_invasion.py
> +    ship = Ship(ai_settings, screen)
I pass the screen as an argument to keep the ship on the screen.

2020-06-25 09:49 UTC, feserr approved these changes

2020-06-25 09:50 UTC, merged